### PR TITLE
improve documentation and styling

### PR DESCRIPTION
**Pull request by marcusvaltonen**
Just applying some of the updates for operators to the rest of the documentation. Found some typos and such as well.

### CODE REVIEW

**Comment by mrava87** [comment]
Nice, this was needed!

From what I can see I think this needs the weighted norm in first as there you define `diag` as macro in the conf.py file. Am I correct?

**Comment by marcusvaltonen** [comment]
Yes, that is okay, but I can move it here instead, that makes more sense.

**Comment by marcusvaltonen** [comment]
The macro \diag is now added

**Comment by marcusvaltonen** [comment]
I found a couple of inconsistencies.

**Comment by mrava87** [comment]
Good idea, then I think this is ready to merge

**Comment by mrava87** [comment]
Documentation built successfully on rtd, done with this :)

**Pull request merged**
