### PR TITLE
Reorganized api index

### PR DESCRIPTION
**Pull request by mrava87**
This PR handles the first suggestion in https://github.com/PyLops/pyproximal/issues/75

### CODE REVIEW

**Comment by mrava87** [comment]
Alright, this sounds reasonable. I first tried to give them some ‘meaningful’ order but I agree that it may not be obvious, alphabetic order is a good choice :)

**Comment by marcusvaltonen** [comment]
You can still do that, but then be explicit with the subheadings:

Vector
- convex
- non-convex
- other

Matrix-only

Still, I would sort everything alphabetically in each subcategory as well.

**Comment by mrava87** [comment]
Alright, let me put it here so we can go back and forth until we agree and then I will implement the changes:

```
Operators

Vector
    
    Convex
         AffineSet
         Box
         Euclidean
         EuclideanBall
         Huber
         Intersection
         L0Ball
         L1
         L1Ball
         L2
         L2Convolve
         L21
         L21_plus_L1
         Quadratic
         Orthogonal
         Simplex
   
    Non-Convex
         ETP
         Geman
         Log
         QuadraticEnvelopeCard
         SCAD
    
    Other
        Nonlinear
        VStack


Matrix-only

    Nuclear
    NuclearBall
    SingularValuePenalty
```

Finally, what about the solvers? There I think the logic of from simpler (ProximalPoint) to more complex (ADMM) holds... do you agree or suggest to go alphabetic as well?

**Comment by mrava87** [comment]
@marcusvaltonen just Edit my comment and change in place :)

**Comment by marcusvaltonen** [comment]
I'm on the phone and editing isn't great.. So I will leave a comment here. First of all, I like the structure (just switch places between Quadratic and Orthogonal).

Regarding the solver. I believe it should be structured in a way that is clear to everyone even though they are new to the field. As long as you document why it is structured in a specific way I think it is fine. However, as the list of solvers continues to grow, the line between which is more "complex" is going to get blurred and at some point I fear it will be completely arbitrary. Then it is just an unsorted list of entries. If it is in alphabetical order at least it is easy to find the documentation, if you are looking for something specific. If you feel strongly about demonstrating the complexity and the benefits of the increased complexity to new users perhaps making tutorials (and linking to them in the docs) is a better long-term solution.

**Comment by mrava87** [comment]
Sounds good, thanks for the feedback!

I agree, eventually also with solvers we may cross the line and then sorting to alphabetic will be the only meaningful way. I will do it now then :) and I agree, our tutorials tend to be what users look at to see what a solver can be used for

**Comment by marcusvaltonen** [comment]
I like it this way. No further comments

**Pull request merged**
