### PR TITLE
Implement Log penalty

### PR DESCRIPTION
**Pull request by marcusvaltonen**
This PR depends on #55 (should be rebased afterwards) I just put it up here so I don't forget it.
This is also one of the methods mentioned in #52 .

### CODE REVIEW

**Comment by mrava87** [comment]
Thanks! Please rebase or make a new PR now that https://github.com/PyLops/pyproximal/pull/55 is in.

**Comment by marcusvaltonen** [comment]
Yes, I'm rebasing it not to clutter the page. I am planning on making one tutorial after I have merged a few of the penalties.

**Comment by marcusvaltonen** [comment]
Not sure why it is failing, should not be related to my fix:

```FAILED pytests/test_projection.py::test_EuclBall[par1] - assert False == True```

**Comment by mrava87** [comment]
Mmh, let me check. I could be that one new test goes in between and since there is no random seed set this test fails. It is a bit strange it does not fail on Linux. I'll make a commit on top of yours once I figure out what it is making this test fail

**Comment by mrava87** [comment]
Fixed :D Shall I merge?

**Comment by marcusvaltonen** [comment]
Go ahead! :)

**Comment by mrava87** [comment]
Great!

**Pull request merged**
